export class PlanOfCareRequestModel {
    id: number;
    activitiesPermitted: string;
    allergies: string;
    caseManager: string;
    clinicalSummary: string;
    comments: string;
    dmEandSupplies: string;
    dose: string;
    freq: string;
    functionalLimitations: string;
    goals: string;
    icD10Code: string;
    icD10Description: string;
    medication: string;
    mentalStatus: string;
    newChg: string;
    notes: string;
    nurseSignature: string;
    nutritionalReq: string;
    onSetEx: string;
    orders: string;
    physician: string;
    prognosis: string;
    qaNotes: string;
    qaStatus: string;
    route: string;
    safetyMeasures: string;
    type: string;
    verbalSOC: string;
    admitDate: string;
    certificationFrom: string;
    certificationTo: string;
    date: string;
    dateReceivedSignedPOC: string;
    dateSenttoPhysician: string;
    signedDate: string;
    constructor() {
        this.id;
        this.activitiesPermitted = "";
        this.allergies = "";
        this.caseManager = "";
        this.clinicalSummary = "";
        this.comments = "";
        this.dmEandSupplies = "";
        this.dose = "";
        this.freq = "";
        this.functionalLimitations = "";
        this.goals = "";
        this.icD10Code = "";
        this.icD10Description = "";
        this.medication = "";
        this.mentalStatus = "";
        this.newChg = "";
        this.notes = "";
        this.nurseSignature = "";
        this.nutritionalReq = "";
        this.onSetEx = "";
        this.orders = "";
        this.physician = "";
        this.prognosis = "";
        this.qaNotes = "";
        this.route = "";
        this.safetyMeasures = "";
        this.type = "";
        this.verbalSOC = "";
        this.admitDate = "";
        this.certificationFrom = "";
        this.certificationTo = "";
        this.date = "";
        this.dateReceivedSignedPOC = "";
        this.dateSenttoPhysician = "";
        this.signedDate = "";
    }
}
