import { CaregiverRequestModel } from "./caregiver-request-model";
import { PersonRequestModel } from "./person-request-model";
import { ClientRequestModel } from "./client-request-model";
import { PayerRequestModel } from "./payer-request-model";
import { PlanOfCareRequestModel } from "./plan-of-care-request-model";
import { ScheduleMasterRequestModel } from "./schedule-master-request-model";
import { BillingCodeRequestModel } from "./BillingCodeRequestModel";
export class ScheduleVisitRequestModel {
id:number;
clientConfirmationFilePath:string;
clientConfirmationType:string;
adjustedEndTime:string;
adjustedStartTime:string;
caregiverLogin:string;
caregiverlogout:string;
endDateTime:string;
startDateTime:string;
isCompleted:number;
isProcessed:number;
billingCodeID:number;
billingCode:number;
caregiverID:number;
caregiver:CaregiverRequestModel;
caregiverPersonID:number;
caregiverPerson:PersonRequestModel;
clientID:number;
client:ClientRequestModel;
clientPersonID:number;
clientPerson:PersonRequestModel;
payerID	:number;
payer:PayerRequestModel;
payerName:string;
pocID:number;
planOfCare:PlanOfCareRequestModel;
scheduleMasterID:number;
scheduleMaster:ScheduleMasterRequestModel;
sequenceId:number;
BillingCode: BillingCodeRequestModel;
status:string;
time:string;
coordinate:string;
startDate:string;

constructor()
{
this.id;
this.clientConfirmationFilePath="";
this.clientConfirmationType="";
this.adjustedEndTime="";
this.adjustedStartTime="";
this.caregiverLogin="";
this.caregiverlogout="";
this.endDateTime="";
this.startDateTime="";
this.isCompleted;
this.isProcessed;
this.billingCodeID;
this.billingCode;
this.caregiverID;
this.caregiver=new CaregiverRequestModel();
this.caregiverPersonID;
this.caregiverPerson=new PersonRequestModel();
this.clientID;
this.client=new ClientRequestModel();
this.clientPersonID;
this.clientPerson=new PersonRequestModel();
this.payerID;
this.payer=new PayerRequestModel();
this.payerName="";
this.pocID;
this.planOfCare=new PlanOfCareRequestModel();
this.scheduleMasterID;
this.scheduleMaster=new ScheduleMasterRequestModel();
this.sequenceId;
this.BillingCode=new BillingCodeRequestModel();
this.status="";
this.time="";
this.coordinate="";
this.startDate="";
}
}
